### ISSUE TITLE
Add logging to the code

### ISSUE THREAD

**Issue by abg-dev** [Saurja/digital-wallet#14]
See this: https://dev.to/geshan/importance-of-logging-in-your-applications-start-logging-today-2om9

Any software must think about logging from the very first day. I didn't see any logs in your code. You need to fix that.

**Comment by Saurja** [comment]
I didn't knew about this, will look itno it from now on.

**Comment by abg-dev** [comment]
No worries. The whole idea of logging is to track down what happened in the system. Once users start using it, if they see an error, you need to help them, right? But, you cannot ask them to share the screen and then troubleshoot. Your only option is to track via log.
